rm -frv A-enst
rm -frv B-enst
rm -frv C-enst
rm -frv D-enst
rm -frv P-enst
rm -frv A-ke
rm -frv B-ke
rm -frv C-ke
rm -frv D-ke
rm -frv P-ke
rm -frv enst
rm -frv ke
rm -frv velocity1
rm -frv velocity2
rm -frv velocity3
rm -frv vorticity1
rm -frv vorticity2
rm -frv vorticity3
rm -frv strain-rates
rm -frv tau
rm -frv cs2
